export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  SEARCH_LIST : "SEARCH_LIST",
  UPDATE_SEARCH_VALUE : "UPDATE_SEARCH_VALUE",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  ADD_CART: "ADD_CART",
  DELETE_CART: "DELETE_CART",
};
