export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FILTERED_PRODUCTS : "FILTERED_PRODUCTS"
  // ADD_CART: "ADD_CART",
  // DELETE_CART: "DELETE_CART",
};
